name: publish

on:
  push:
    branches:
    - deploy
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout branch "deploy"
      uses: actions/checkout@v2
      with:
        ref: 'deploy'
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.62.2'

    - name: Build
      run: hugo --minify
      
    - name: Copy readme
      run: |
        cp ./README.md ./public/README.md
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public